# Generated by Django 3.2.7 on 2021-10-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='device.location',
            ),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='devices',
                to='device.devicetype',
            ),
        ),
        migrations.CreateModel(
            name='DevicePin',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=32)),
                ('identifier', models.SlugField(max_length=64)),
                ('pin_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('analog', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('rule', models.JSONField()),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pins',
                        to='device.device',
                    ),
                ),
            ],
        ),
    ]
