# Generated by Django 4.0.4 on 2022-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20211006_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepin',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
