# Generated by Django 4.1 on 2022-11-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_remove_devicepin_device_devicepin_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehealth',
            name='status',
        ),
    ]
