# Generated by Django 4.1.7 on 2023-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_remove_devicehealth_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Device Statuses',
            },
        ),
        migrations.AddField(
            model_name='devicepin',
            name='display',
            field=models.JSONField(null=True),
        ),
    ]
