# Generated by Django 4.1.7 on 2023-03-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_alter_devicestatus_options_devicepin_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepin',
            name='i2c',
            field=models.BooleanField(default=False),
        ),
    ]
