# Generated by Django 4.2.5 on 2023-10-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_devicepin_i2c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicepin',
            old_name='device',
            new_name='devices',
        ),
    ]
