# Generated by Django 4.2.6 on 2025-11-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_rename_device_devicepin_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePinType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=32)),
                ('identifier', models.SlugField(max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicetype',
            name='identifier',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicepin',
            name='type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pins',
                to='device.devicepintype',
            ),
        ),
    ]
