# Generated by Django 5.2.17 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0011_devicepintype_devicetype_identifier_devicepin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='managed_firmware',
            field=models.BooleanField(default=True),
        ),
    ]
