# Generated by Django 5.2.17 on 2026-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0013_alter_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonoffToken',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('access_token_expires_at', models.DateTimeField()),
                ('refresh_token_expires_at', models.DateTimeField()),
                ('region', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sonoff Token',
            },
        ),
    ]
