# Generated by Django 5.2.17 on 2026-09-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0014_sonofftoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepin',
            name='display',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
