# Generated by Django 5.2.17 on 2026-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0015_alter_devicepin_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehealth',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehealth',
            name='wifi_signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
